Updates

diff --git a/.github/workflows/gcms_plugin_version_updater_workflow.yml b/.github/workflows/gcms_plugin_version_updater_workflow.yml
--- a/.github/workflows/gcms_plugin_version_updater_workflow.yml
+++ b/.github/workflows/gcms_plugin_version_updater_workflow.yml
@@ -78,16 +78,16 @@ jobs:
             echo "$TMP_VERIFY_VERSION"
             echo "-----END-----"
           
-            TMP_COUNT_VERSIONS="$(printf "%d\n" "$TMP_VERIFY_VERSION | wc -l")"
+            # TMP_COUNT_VERSIONS="$(printf "%d\n" "$TMP_VERIFY_VERSION | wc -l")"
 
-            echo "$TMP_COUNT_VERSIONS"
+            # echo "$TMP_COUNT_VERSIONS"
 
-            if [[ ${TMP_COUNT_VERSIONS} > 0 ]]; then
-              TMP_MSG="Fail to replace all the ${UNDEFINED_VERSION} (find $TMP_COUNT_VERSIONS occurrences)"
-              echo "::error:: ${TMP_MSG}"
-              echo "➕ ${TMP_MSG}" >> $GITHUB_STEP_SUMMARY
-              exit 1
-            fi
+            # if [[ ${TMP_COUNT_VERSIONS} > 0 ]]; then
+            #   TMP_MSG="Fail to replace all the ${UNDEFINED_VERSION} (find $TMP_COUNT_VERSIONS occurrences)"
+            #   echo "::error:: ${TMP_MSG}"
+            #   echo "➕ ${TMP_MSG}" >> $GITHUB_STEP_SUMMARY
+            #   exit 1
+            # fi
 
           else
             echo "🎉 No occurrences found. Patching fully done."
